apiVersion: certmanager.k8s.io/v1beta1
kind: Certificate
metadata:
  name: ginawitech-net-tls
spec:
  secretName: ginawitech-net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: ginawitech.net
  dnsNames:
    - ginawitech.net
    - www.ginawitech.net
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - ginawitech.net
          - www.ginawitech.net